enhancement: Add Error Handling for Missing Input Fields
atj393/promt-save-reuse-chatgpt-and-gemini pull request #26
Opened 2024-10-09 07:15 UTC by om-3004

# Fixes #7 (Add Error Handling for Missing Input Fields)

Added an alert that displays a message when the input field is left empty.

## Screenshots
### Nothing typed - ChatGPT
![Screenshot 2024-10-09 123935](https://github.com/user-attachments/assets/b8ecfe31-e742-444b-9dee-57dfd74a7755)
### White Spaces - ChatGPT
![Screenshot 2024-10-09 123957](https://github.com/user-attachments/assets/f81adeef-07c6-4713-a2f4-1a2b7eb212f3)
### Multiple empty lines - ChatGPT
![Screenshot 2024-10-09 124013](https://github.com/user-attachments/assets/c9b353b0-8c56-4be6-a54f-bcb8dbabece6)
### Nothing types - Gemini
![Screenshot 2024-10-09 124037](https://github.com/user-attachments/assets/04e2331a-2d7f-4fcf-ba47-b8b4b235160f)
### White Spaces - Gemini
![Screenshot 2024-10-09 124050](https://github.com/user-attachments/assets/efde1317-8e63-479b-8687-4fc89ea7e52c)

2024-10-09 07:17 UTC, om-3004 commented
Hello @atj393, Please find and review my PR and let me know if there are any issues.

2024-10-09 08:15 UTC, atj393 commented
@om-3004 Great work! Thanks for the attached screenshot. I will review all the changes together at the end of the day.
- Question, have you merged the latest changes from the main branch to the forked branch?
-Discussion, can we use a small notification popup instead of an alert? Is it possible? How much effort do you think it will take?

2024-10-09 10:18 UTC, om-3004 commented
Thank you @atj393 !!

- Yes, I have merged the latest changes from the main branch. And I did checkout a new branch and commit the code changes in that branch. 

![Screenshot 2024-10-09 140515](https://github.com/user-attachments/assets/871ce320-22c2-40ce-9804-b37fa005fc7b)

- For the notification popup, we can use WebNotifications API which will not take up much effort. It looks like this:

![Screenshot 2024-10-09 153233](https://github.com/user-attachments/assets/3131fe11-78a2-48bc-81ec-24f1ec6031cb)

- We can also make our custom notification pop-up box with using CSS or we can use any library by installing it from npm.

2024-10-09 12:36 UTC, om-3004 commented
Hello @atj393 , I've committed the change of showing message by WebNotification API which is auto dismissed after 5 seconds. Please check and let me know if there is something to update/add. Thanks

2024-10-09 12:39 UTC, om-3004 commented
Here is the screen recording of it:
https://github.com/user-attachments/assets/41315b48-c7e9-4a4e-a554-b96a954ebdb8

2024-10-09 13:09 UTC, atj393 commented
@om-3004 Great work! Thanks.

I will review the code and merge the request by EOD. Let you know soon!

2024-10-09 19:34 UTC, atj393 commented
@om-3004 This isn't working for me. I checked out your branch and tested it locally, but the notifications aren't appearing.
Please see the attached video.
[screen-capture.webm](https://github.com/user-attachments/assets/4ecba0ad-a39f-4744-9a5a-2791d6a06ebe)

2024-10-10 04:31 UTC, om-3004 commented
Hello @atj393 , sorry I think I forgot to add permission for notifications. I have added that manifest file in the latest commit. Please check if that works now.

2024-10-10 11:49 UTC, om-3004 commented
@atj393 Also the notifications might have been blocked in your browser, in which case the notification won't pop. So you can try by resetting the notification permission to 'default'.

There are 3 permissions for the notifications:
1.  Granted - The notification will show up
2.  Default - We can request for permission (Allow/Block)
3.  Denied - The notification won't pop

So I was thinking in case the permission is denied, maybe we can show alert to the user to change the permission for notifications.

2024-10-15 20:51 UTC, atj393 commented
@om-3004 Thank you for your response.
I have tried enabling the permissions and also verified that the permission type was 'default' while checking.

I will review it again within 2 days and finalize it. Thanks.

2024-10-16 21:16 UTC, atj393 commented
@om-3004 I could not able to replicate it again.

2024-10-17 12:42 UTC, om-3004 commented
@atj393 let me see if I can find something about the notifications.

2024-10-18 06:25 UTC, om-3004 commented
- @atj393 I've added alert if the notification permission is set to `block`.
- If it is set to `ask/default`, request for permission.
- And it is set to `allow` the notification is poped up.

https://github.com/user-attachments/assets/49aa13b4-a532-429a-81a9-ba56cea98dc1

2024-10-18 09:43 UTC, atj393 commented
@om-3004 I will check it tonight. Thanks.

2024-10-18 09:44 UTC, atj393 commented
@om-3004 meantime can you resolve the conflicts?

2024-10-18 10:17 UTC, om-3004 commented
@atj393 I've merged the main with my feature branch and resolved the merge conflicts. Please check and let me know if there is any issue.

2024-10-18 13:21 UTC, atj393 requested changes

2024-10-18 13:21 UTC, atj393 commented on background.js
> -  const inputFieldChatGPT =
@om-3004 Why is this selector removed? it is the fix for the bug #4

2024-10-19 03:54 UTC, om-3004 commented
@atj393 I've updated that lines of code, please verify.

2024-10-19 10:53 UTC, atj393 approved these changes
@om-3004 Great Work. I am merging the changes. Thanks for your efforts!

2024-10-19 10:54 UTC, merged